### ISSUE TITLE
hybridgroup-serialport is not included in debian installation

### ISSUE THREAD

**Issue by madebydavid** [hybridgroup/kidsrubyinstaller-debian#2]
Procedure followed:
- Fresh install of Ubuntu 13.10
- Download kidsruby .deb file from kidsruby.com
- `$ dpkg --install kidsruby-1.4.0-i686`
- Followed the pairing instructions on https://github.com/hybridgroup/sphero/blob/master/README.markdown
- Enter the code for the Sphero example
- Click "Run"

Expected results:

Kidsruby should communicate with the Sphero device

Actual results:

```
Please 'gem install hybridgroup-serialport' for serial port support.
can't convert nil to IO
```

**Comment by zankich** [comment]
@madebydavid I'll add it!

In the meantime you may connect to the sphero using socat

```
$ sudo apt-get install socat
```

Then follow the steps here https://github.com/hybridgroup/sphero/blob/master/README.markdown#pairing-sphero-with-ubuntu

Then initiate the serial connection with

```
$ socat FILE:/dev/rfcomm0,nonblock,raw,b115200,echo=0 TCP-LISTEN:4560,fork,keepalive
```

And set your sphero address to `127.0.0.1:4560`

**Comment by madebydavid** [comment]
Hey! First of all, many thanks for getting back to me so quickly; really appreciate it.

I have tried your suggested fix with socat - the sphero changes to blue when socat runs, I presume to indicate that we have connected to it. However, we still cannot connect from KidsRuby, even if we change the address like this:

``` ruby
require 'sphero'
Sphero.start '127.0.0.1:4560' do
  roll 60, FORWARD
end
```

We receive the same error message "can't convert nil to IO". 

So, instead I performed the following:

``` bash
$ cd /usr/local/kidsruby/ruby/bin
$ ./gem install hybridgroup-serialport
```

However, after this, I then received this error:

```
Transport endpoint is not connected
/usr/local/kidsruby/vendor/ruby/1.9.1/gems/hybridgroup-sphero-1.4.0/lib/sphero.rb:182:in `write': Transport endpoint is not connected (Errno::ENOTCONN)
        from /usr/local/kidsruby/vendor/ruby/1.9.1/gems/hybridgroup-sphero-1.4.0/lib/sphero.rb:182:in `block in write'
        from :10:in `synchronize'
        from /usr/local/kidsruby/vendor/ruby/1.9.1/gems/hybridgroup-sphero-1.4.0/lib/sphero.rb:181:in `write'
        from /usr/local/kidsruby/vendor/ruby/1.9.1/gems/hybridgroup-sphero-1.4.0/lib/sphero.rb:95:in `roll'
        from /tmp/kidcode.rb:6:in `block in '
        from /usr/local/kidsruby/vendor/ruby/1.9.1/gems/hybridgroup-sphero-1.4.0/lib/sphero.rb:24:in `instance_eval'
        from /usr/local/kidsruby/vendor/ruby/1.9.1/gems/hybridgroup-sphero-1.4.0/lib/sphero.rb:24:in `start'
        from /tmp/kidcode.rb:5:in `'
```

So, I ran the following:

``` bash
$ sudo rfcomm release /dev/rfcomm0
$ sudo rfcomm connect /dev/rfcomm0 <address> 1
```

Note the `connect` instead of the `bind`. At this point the Sphero turned blue and when I clicked Run in KidsRuby it worked.

So, think maybe you also have a documentation issue?

**Comment by deadprogram** [comment]
Sounds like we need to update docs, but also include socat or some equivalent in KidsRuby on Linux. The binary serialport gem builds are tricky enough for Windows & OSX already.
